### ISSUE TITLE
Consider using react-transform-webpack-hmr instead of react-hot-loader

### ISSUE THREAD

**Issue by andreypopp** [insin/react-heatpack#9]
See https://github.com/gaearon/react-transform-boilerplate

It also uses `react-proxy` and so supports `autobind-decorator` and ES5.1 getters/setters and such.

**Comment by insin** [comment]
:+1:

**Comment by insin** [comment]
This appears to be fiddly because Babel now assumes responsibility for loading modules, will create a branch with progress I had soon.
